---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lasample-qa
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: rsuslov/gitops:hellov1.2
---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: lasample-qa
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 32321
  type: NodePort
